services:
  api:
    image: iszifyapi
    container_name: iszify_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7000:7000
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
        - redis

  redis:
    image: redis
    container_name: iszify_redis
    ports:
      - 6379:6379

  nginx:
    image: nginx
    container_name: iszify_nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      - redis
