# Base image
FROM nginx:latest

# Install Certbot
RUN apt-get update && \
    apt-get install -y certbot && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Copy the nginx config file to the container
COPY ./nginx.conf /etc/nginx/nginx.conf

# Expose ports
EXPOSE 80 443

# Command to run Nginx
CMD ["nginx", "-g", "daemon off;"]
