services:
  api:
    image: iszifyapi
    container_name: iszify_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7000:7000
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
        - redis

  redis:
    image: redis
    container_name: iszify_redis
    ports:
      - 6379:6379

  nginx:
    image: nginx
    container_name: iszify_nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs
    depends_on:
      - api
      - redis
    command:
      - /bin/sh
      - -c
      - |
        apt-get update && apt-get install -y certbot \
        && certbot certonly --non-interactive --agree-tos --email israelwonahtb@gmail.com \
        --standalone -d iszz.ly -d www.iszz.ly