name: Deploy Api
run-name: Deploy - ${{ github.event.head_commit.message }}
on:
  push:
    branches:
    - main

jobs:
  Api-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Deploy to VM
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        command_timeout: 30m
        script: |
            cd IszifyAPI/

            git pull origin main

            docker compose up --build -d --force-recreate

            docker image prune -f